### PR TITLE
Create default SECURITY.md

### PR DESCRIPTION
**Pull request by mbarbero**
Default security policy from Eclipse Foundation's recommendations https://gitlab.eclipse.org/security/best-practices/

### CODE REVIEW

**Comment by mbarbero** [comment]
Any interest in this one? 
/cc @vietj

**Comment by vietj** [comment]
Actually we have a policy in the project to support the previous major version up to 2 years after the release of the current major (to let community upgrade to the current major), e.g. we have been supporting Vert.x 3.9.x releases until 6 months ago, currently 3.9.x is not officially supported anymore since Vert.x 4.0.0 has been released more than 2 years ago. Can we update the document to mention ? @mbarbero

**Comment by mbarbero** [comment]
> Can we update the document to mention ? @mbarbero

Done ✅

**Review by vietj — APPROVED** [review]

**Comment by mbarbero** [comment]
Gentle ping. Thanks!

**Comment by mbarbero** [comment]
Is there anything in the proposed policy that you would like to see edited before merging it? Thanks!

**Comment by vietj** [comment]
@mbarbero it looks good to me, if I think about something relevant I'll open an issue, sorry for the delay

**Review by vietj — APPROVED** [review]

**Comment by mbarbero** [comment]
> @mbarbero it looks good to me, if I think about something relevant I'll open an issue, sorry for the delay

It's still only approved, not merged :)

**Comment by vietj** [comment]
shall I merge it ?

**Comment by mbarbero** [comment]
> shall I merge it ?

If you're ok with the content, yes, please. I'm not a committer and don't have write permission on your repositories :)

**Comment by vietj** [comment]
@mbarbero oh right I didn't realise this

**Pull request merged**
