### PR TITLE
update the real vertx.svg

### PR DESCRIPTION
**Pull request by okou19900722**
Signed-off-by: okou19900722 <ilayan19900722@gmail.com>

### CODE REVIEW

**Comment by vietj** [comment]
what does this PR do ? it's not clear

**Comment by okou19900722** [comment]
The current icon seems to be inconsistent with the icon on the official website, I drew an icon the same as the official website

**Comment by okou19900722** [comment]
now:

image
my svg icon: 
image

**Comment by michel-kraemer** [comment]
@okou19900722 and @vietj I'm not sure from where you took this icon, but the most up-to-date version from the latest 4.x website is here:
https://github.com/vertx-web-site/vertx-web-site/blob/master/assets/vertx-favicon.svg

**Comment by okou19900722** [comment]
@michel-kraemer I made it by myself

**Comment by michel-kraemer** [comment]
Thanks for the effort, but I think we should use the official one. If you like you can update your PR.

**Pull request closed without merging**
